name: Tafwila
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.0.6 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  drop_down_list: ^0.0.6
  geolocator: ^10.1.0
  flutter_test:
    sdk: flutter
  http: ^1.1.0
  shared_preferences: ^2.2.2
  firebase_core: ^2.24.2
  cloud_firestore: ^4.14.0
  firebase_storage: ^11.6.0
  firebase_messaging: ^14.7.10
  firebase_auth: ^4.16.0
  google_sign_in: ^6.1.6
  awesome_dialog: ^3.2.0
  google_maps_flutter: ^2.5.3
  geocoding: ^3.0.0
  chat_bubbles: ^1.6.0
  flutter_polyline_points: ^2.0.0
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.4

  


flutter_test:
  sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
     - images/

flutter_icons:
  android: true
  ios: true
  image_path: "images/11.jpg"
  adaptive_icon_foreground: "images/11.jpg"
  adaptive_icon_background: "#E57734"
  min_sdk_android: 21
  remove_alpha_ios: true

flutter_native_splash:
  background_image: "images/11.jpg"
  android: true
  ios: true
  web: false
  fullscreen: true
  android_12:
    image: "images/11.jpg"
    icon_background_color: "#ffffff"
    